# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_movieuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieuser',
            old_name='movies_want',
            new_name='movies_want_set',
        ),
        migrations.RenameField(
            model_name='movieuser',
            old_name='movies_watched',
            new_name='movies_watched_set',
        ),
    ]
