# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 19:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170224_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='users',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='watched',
        ),
        migrations.AlterField(
            model_name='movieuser',
            name='movies_want_set',
            field=models.ManyToManyField(blank=True, related_name='users_want', to='api.Movie'),
        ),
        migrations.AlterField(
            model_name='movieuser',
            name='movies_watched_set',
            field=models.ManyToManyField(blank=True, related_name='users_watched', to='api.Movie'),
        ),
        migrations.AlterField(
            model_name='movieuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='movieuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
